---
deployment:
  tasks:
  #  - export DEPLOYPATH=/home/ckcodete/helloworld/public_html/
    - export DEPLOYPATH=/home/ckcodete/helloworld/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp README.md $DEPLOYPATH